services:
  - type: web
    name: novayshop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 novayshop.py
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
